name: Push to Production

on:
  push:
    branches: [ master ] # Only trigger on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for existing agent
        run: |
          if ps aux | grep -v grep | grep ssh-agent; then
            echo "Existing SSH agent found. Stopping it...";
            pkill ssh-agent;
          fi
      - name: Set SSH socket and PID variables
        run: |
          export SSH_AUTH_SOCK=/tmp/ssh-XXXXXXFUOwJ2/agent.1754
          export SSH_AGENT_PID=1757
      - name: Verify agent connection
        run: |
          if ! ssh-add -l; then
            echo "Error: Could not connect to SSH agent";
            exit 1;
          fi
      - name: Add SSH key to agent
        run: echo "$SSH_PRIVATE_KEY" | ssh-add -i -
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }}
      - run: git push prod-1 HEAD # Push changes to the production remote named 'prod-1'

