name: Push to Production

on:
  push:
    branches: [ master ] # Only trigger on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start SSH agent
        run: |
          ssh-agent -s &
          echo "$SSH_PRIVATE_KEY" | ssh-add -i -
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }}
      - run: git push prod-1 HEAD # Push changes to the production remote named 'prod-1'

