name: Push to Production

on:
  push:
    branches: [ master ] # Only trigger on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git push prod-1 master 

env:
  SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }} 
