name: Sync with Remote

on:
  push:
    branches:
      - master  # Change this to your master branch name

jobs:
  sync-with-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p $HOME/.ssh

      - name: Add SSH key
        run: |
          echo "${{ secrets.PROD_SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Ensure known_hosts file exists
        run: touch $HOME/.ssh/known_hosts

      - name: Remove Old Key from Known Hosts
        run: ssh-keygen -R 13.200.152.101
        # Replace "13.200.152.101" with your server's IP address or domain

      - name: Record the Updated Key
        run: ssh-keyscan -t rsa 13.200.152.101 >> $HOME/.ssh/known_hosts
        # Replace "13.200.152.101" with your server's IP address or domain

      - name: Add Remote
        run: git remote add production ec2-user@13.200.152.101:/var/www/test/test-repo.git
        # Replace "remote-name" with your desired remote name and update the path to your repository

      - name: Push to Remote
        run: git push production master  # Change "master" to your master branch name
